"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, Bus, Car, Clock3, Map, SlidersHorizontal, Star, UsersRound } from "lucide-react";
import { Footer, Header } from "../components";
import { schedules } from "../data";
import { useBooking } from "../store";
import { TravelMode } from "../types";

const modes:{id:"all"|TravelMode;label:string}[]=[{id:"all",label:"All rides"},{id:"bus",label:"Coach"},{id:"cab",label:"Private cab"},{id:"tempo",label:"Tempo"},{id:"airport",label:"Airport"}];
export default function SearchPage(){const {booking,update}=useBooking();const router=useRouter();const [mode,setMode]=useState<"all"|TravelMode>("all");const [sort,setSort]=useState("recommended");const [view,setView]=useState("list");
 const list=useMemo(()=>schedules.filter(x=>mode==="all"||x.mode===mode).sort((a,b)=>sort==="price"?a.price-b.price:sort==="fast"?a.duration.localeCompare(b.duration):b.rating-a.rating),[mode,sort]);
 const choose=(id:string)=>{update({scheduleId:id,seats:[],addOns:[]});router.push("/trip/demo")};
 return <><Header/><main className="page"><div className="search-heading"><div><span className="eyebrow">Available journeys</span><h1>{booking.search.from} <ArrowRight/> {booking.search.to}</h1><p>12 October · {booking.search.travellers} travellers · {list.length} rides</p></div><button className="outline"><SlidersHorizontal/> Modify search</button></div>
 <div className="filters"><div>{modes.map(m=><button className={mode===m.id?"active":""} onClick={()=>setMode(m.id)} key={m.id}>{m.label}</button>)}</div><select aria-label="Sort rides" value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="price">Lowest price</option><option value="fast">Fastest</option></select><div className="view-toggle"><button className={view==="list"?"active":""} onClick={()=>setView("list")}>List</button><button className={view==="map"?"active":""} onClick={()=>setView("map")}><Map/> Map</button></div></div>
 {view==="map"?<div className="map-view"><div className="map-label delhi">New Delhi<i/></div><svg viewBox="0 0 600 340"><path d="M115 65 C180 100 210 90 260 150 S390 220 480 275"/><path className="route-path" d="M115 65 C180 100 210 90 260 150 S390 220 480 275"/></svg><div className="map-label jaipur">Jaipur<i/></div><div className="map-card"><b>281 km</b><span>Estimated travel · 4h 45m</span><button onClick={()=>setView("list")}>View {list.length} rides</button></div></div>:<div className="results"><AnimatePresence mode="popLayout">{list.map((trip,i)=><motion.article layout key={trip.id} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{delay:i*.04}} className="result-card"><div className="vehicle-icon">{trip.mode==="bus"?<Bus/>:<Car/>}</div><div className="result-main"><div className="result-top"><div><span className="eyebrow">{trip.name}</span><h2>{trip.vehicle}</h2></div><span><Star fill="currentColor"/> {trip.rating}</span></div><div className="journey"><div><b>{trip.departure}</b><span>{booking.search.from}</span></div><div className="duration"><span>{trip.duration}</span><i/><small>281 km</small></div><div><b>{trip.arrival}</b><span>{booking.search.to}</span></div></div><div className="amenities">{trip.amenities.slice(0,3).map(x=><span key={x}>{x}</span>)}<span className={trip.seatsLeft<4?"scarce":""}>{trip.seatsLeft} seats left</span></div></div><div className="result-price"><small>from</small><b>₹{trip.price.toLocaleString("en-IN")}</b><span>incl. taxes</span><button onClick={()=>choose(trip.id)}>View journey <ArrowRight/></button></div></motion.article>)}</AnimatePresence></div>}
 <section className="reassurance"><div><Clock3/><b>Clear schedules</b><span>Know exactly when you leave and arrive.</span></div><div><UsersRound/><b>Real comfort</b><span>Every ride is chosen with care.</span></div><div><Star/><b>Traveller rated</b><span>Honest feedback from real journeys.</span></div></section></main><Footer/></>}
