"use client";
import Link from "next/link";import {usePathname} from "next/navigation";import {useState} from "react";
import {Activity,AlertTriangle,BarChart3,Bell,CalendarDays,ChevronDown,CircleDollarSign,Container,FileText,LayoutDashboard,Map,Menu,MessageSquare,Package,Route,Search,Settings,ShieldCheck,Truck,Users,X} from "lucide-react";
import {useOps} from "../lib/store";import {Role} from "../lib/types";
const nav=[
 ["Overview","/",LayoutDashboard],["Live map","/live-map",Map],["Orders","/orders",Package],["Fleet","/fleet",Truck],["Drivers","/drivers",Users],["Routes","/routes",Route],["Calendar","/calendar",CalendarDays],
 ["Analytics","/analytics",BarChart3],["Finance","/finance",CircleDollarSign],["Documents","/documents",FileText],["Messages","/messages",MessageSquare],["Alerts","/alerts",AlertTriangle],["Users","/users",ShieldCheck],["Settings","/settings",Settings]
] as const;
export function Shell({children,title,subtitle,actions}:{children:React.ReactNode;title?:string;subtitle?:string;actions?:React.ReactNode}){const path=usePathname();const [open,setOpen]=useState(false);const {state,setRole,setQuery,unresolved}=useOps();return <div className="app-shell">
 <aside className={open?"sidebar open":"sidebar"}><div className="logo"><i><Container/></i><span>Rovia<em>Logistics</em></span><button onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div><nav>{nav.map(([label,href,Icon])=><Link onClick={()=>setOpen(false)} key={href} className={path===href||href!=="/"&&path.startsWith(href)?"active":""} href={href}><Icon/><span>{label}</span>{label==="Alerts"&&unresolved.length>0?<b>{unresolved.length}</b>:null}{label==="Messages"&&<b>3</b>}</Link>)}</nav><div className="side-foot"><Activity/><div><b>All systems operational</b><span>Last sync · just now</span></div></div></aside>
 <div className="workspace"><header className="topbar"><button className="hamburger" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu/></button><div className="global-search"><Search/><input aria-label="Global search" placeholder="Search order, vehicle, driver…" value={state.filters.query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><div className="top-actions"><Link href="/alerts" aria-label={`${unresolved.length} notifications`} className="icon-button"><Bell/><i>{unresolved.length}</i></Link><label className="role"><span>{state.role}</span><select aria-label="Switch demo role" value={state.role} onChange={e=>setRole(e.target.value as Role)}><option>Admin</option><option>Dispatcher</option><option>Fleet Manager</option></select><ChevronDown/></label><div className="avatar">AS</div></div></header>
 <main className="content">{title&&<div className="page-head"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</div>}{children}</main><MobileNav path={path}/></div>{open&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}</div>}
function MobileNav({path}:{path:string}){return <nav className="mobile-tabs">{nav.slice(0,5).map(([label,href,Icon])=><Link key={href} className={path===href?"active":""} href={href}><Icon/><span>{label}</span></Link>)}</nav>}
