"use client";
import {AlertCircle,ArrowDownRight,ArrowUpRight,CheckCircle2,ChevronRight,Clock3,Download,MoreHorizontal,Package,Truck,X} from "lucide-react";import Link from "next/link";import {useState} from "react";
import {Shipment,ShipmentStatus} from "../lib/types";import {statusOrder,useOps} from "../lib/store";
export const inr=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
export function Status({value}:{value:string}){return <span className={`status s-${value.toLowerCase().replaceAll(" ","-")}`}><i/>{value}</span>}
export function Kpi({label,value,delta,icon:Icon,tone="neutral"}:{label:string;value:string;delta?:string;icon:React.ElementType;tone?:string}){return <article className={`kpi ${tone}`}><div><span>{label}</span><Icon/></div><b>{value}</b>{delta&&<small className={delta.startsWith("-")?"down":"up"}>{delta.startsWith("-")?<ArrowDownRight/>:<ArrowUpRight/>}{delta.replace("-","")} vs last week</small>}</article>}
export function ShipmentTable({limit,shipments}:{limit?:number;shipments?:Shipment[]}){const {state}=useOps();const list=(shipments||state.shipments).slice(0,limit||999);return <div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Route</th><th>Vehicle</th><th>ETA</th><th>Status</th><th>Value</th><th/></tr></thead><tbody>{list.map(s=><tr key={s.id}><td><Link className="order-id" href={`/orders/${s.id}`}>{s.id}</Link><small>{s.priority}</small></td><td>{s.customer}</td><td><b>{s.origin}</b><ChevronRight/><b>{s.destination}</b></td><td>{state.vehicles.find(v=>v.id===s.vehicleId)?.registration||"Unassigned"}</td><td>{s.eta}</td><td><Status value={s.status}/></td><td>{inr(s.value)}</td><td><button className="dots" aria-label={`Actions for ${s.id}`}><MoreHorizontal/></button></td></tr>)}</tbody></table>{list.length===0&&<Empty title="No matching orders"/>}</div>}
export function Empty({title="Nothing here yet"}:{title?:string}){return <div className="empty"><Package/><b>{title}</b><span>Try changing the active filters.</span></div>}
export function PermissionButton({area,children,...rest}:{area:string;children:React.ReactNode;[key:string]:unknown}){const {can,state}=useOps();return <button disabled={!can(area)} title={!can(area)?`${state.role} cannot perform this action`:undefined} {...rest}>{children}</button>}
export function CreateShipment({open,onClose}:{open:boolean;onClose:()=>void}){const {createShipment}=useOps();const [form,setForm]=useState({customer:"",origin:"New Delhi",destination:"Jaipur",weight:"",priority:"Standard"});const [error,setError]=useState("");if(!open)return null;const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.customer||!form.weight){setError("Customer and weight are required.");return}const id=`RVL-DEMO-${Math.min(12,Number(localStorage.getItem("rovia:demo-count")||0)+1)}`;localStorage.setItem("rovia:demo-count",String(Number(id.split("-").at(-1))));createShipment({id,customer:form.customer,origin:form.origin,destination:form.destination,status:"Pending",priority:form.priority as Shipment["priority"],weight:+form.weight,value:+form.weight*32,progress:0,eta:"Awaiting assignment",created:"Today",notes:"",cargo:[],stops:[],events:[]});onClose()};return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="drawer" onSubmit={submit}><header><div><span>New shipment</span><h2>Create an order</h2></div><button type="button" onClick={onClose}><X/></button></header><label>Customer<input value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})} placeholder="Company name"/></label><div className="form-row"><label>Origin<select value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}>{["New Delhi","Mumbai","Bengaluru","Chennai","Hyderabad","Kolkata","Lucknow"].map(x=><option key={x}>{x}</option>)}</select></label><label>Destination<select value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}>{["Jaipur","Pune","Chennai","Hyderabad","Ahmedabad","Lucknow","Delhi NCR"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="form-row"><label>Weight (kg)<input type="number" min="1" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Standard</option><option>Express</option><option>Critical</option></select></label></div>{error&&<p className="form-error"><AlertCircle/>{error}</p>}<div className="drawer-summary"><Truck/><div><b>{form.origin} → {form.destination}</b><span>Resources can be assigned after creation</span></div></div><footer><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Create shipment</button></footer></form></div>}
export function StatusSelect({shipment}:{shipment:Shipment}){const {updateShipment,can,state}=useOps();return <select className="status-select" disabled={!can("orders")} title={!can("orders")?`${state.role} cannot change shipment status`:undefined} value={shipment.status} onChange={e=>updateShipment(shipment.id,{status:e.target.value as ShipmentStatus,progress:e.target.value==="Delivered"?100:shipment.progress})}>{statusOrder.map(x=><option key={x}>{x}</option>)}</select>}
export function ExportButton({filename="rovia-export.csv"}:{filename?:string}){const exportIt=()=>{const blob=new Blob(["id,status,value\nRVL-58461,In Transit,284000"],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href)};return <button className="button secondary" onClick={exportIt}><Download/> Export CSV</button>}
export function AlertIcon({type}:{type:string}){return type==="Delay"?<Clock3/>:type==="Maintenance"?<Truck/>:type==="Deviation"?<AlertCircle/>:<CheckCircle2/>}
