"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, CreditCard, Landmark, LoaderCircle, ShieldCheck, Smartphone } from "lucide-react";
import { Back, BookingSummary, Header, Progress } from "../components";
import { useBooking } from "../store";

export default function Checkout(){const {booking,update,total}=useBooking();const [errors,setErrors]=useState<Record<string,string>>({});const [processing,setProcessing]=useState(false);const [stage,setStage]=useState(0);const router=useRouter();
 const set=(key:string,value:string)=>update({traveller:{...booking.traveller,[key]:value}});
 const submit=(e:FormEvent)=>{e.preventDefault();const t=booking.traveller;const next:Record<string,string>={};if(t.name.trim().length<2)next.name="Enter your full name";if(!/^\d{10}$/.test(t.phone))next.phone="Enter a valid 10-digit mobile number";if(!/^\S+@\S+\.\S+$/.test(t.email))next.email="Enter a valid email";if(!t.age||+t.age<5)next.age="Enter a valid age";if(!t.gender)next.gender="Select an option";setErrors(next);if(Object.keys(next).length)return;setProcessing(true);[1,2,3].forEach((x,i)=>setTimeout(()=>setStage(x),(i+1)*850));setTimeout(()=>router.push("/booking-confirmed"),3500)};
 return <><Header/><main className="page booking-page"><Back href="/select-seat" label="Seats & extras"/><Progress step={2}/><form className="booking-grid" onSubmit={submit}><div><section className="traveller-form"><span className="eyebrow">Traveller details</span><h1>Who&apos;s making the journey?</h1><div className="form-grid"><Field label="Full name" value={booking.traveller.name} error={errors.name} onChange={v=>set("name",v)} placeholder="Aarav Mehta"/><Field label="Mobile number (+91)" value={booking.traveller.phone} error={errors.phone} onChange={v=>set("phone",v)} placeholder="98765 43210" inputMode="numeric"/><Field label="Email address" value={booking.traveller.email} error={errors.email} onChange={v=>set("email",v)} placeholder="aarav@example.com" type="email"/><Field label="Age" value={booking.traveller.age} error={errors.age} onChange={v=>set("age",v)} placeholder="32" inputMode="numeric"/><label className={errors.gender?"error":""}><span>Gender</span><select value={booking.traveller.gender} onChange={e=>set("gender",e.target.value)}><option value="">Select</option><option>Male</option><option>Female</option><option>Non-binary</option><option>Prefer not to say</option></select><small>{errors.gender}</small></label></div></section><section className="payment"><span className="eyebrow">Payment method</span><h2>Choose how you&apos;d like to pay.</h2><div className="payment-tabs">{[["upi","UPI",Smartphone],["card","Cards",CreditCard],["bank","Net banking",Landmark]].map(([id,label,Icon])=><button type="button" className={booking.payment===id?"active":""} onClick={()=>update({payment:id as string})} key={id as string}><Icon/><span>{label as string}</span></button>)}</div>{booking.payment==="upi"&&<label className="upi"><span>UPI ID</span><div><input placeholder="name@upi"/><button type="button">Verify</button></div><small>Try any demo UPI ID. No real payment is made.</small></label>}{booking.payment==="card"&&<div className="demo-note"><CreditCard/>This is a simulated card payment. No card details are required.</div>}{booking.payment==="bank"&&<div className="demo-note"><Landmark/>Choose any bank during the simulated confirmation.</div>}<div className="secure"><ShieldCheck/>Secure demo checkout · no financial data is stored</div></section></div><div><BookingSummary/><button className="primary wide" type="submit">Pay ₹{total.toLocaleString("en-IN")}</button></div></form></main>{processing&&<div className="processing" role="status"><div className={stage===3?"done":""}>{stage===3?<Check/>:<LoaderCircle/>}</div><h2>{["Securing your seats…","Securing your seats…","Confirming your journey…","Booking confirmed"][stage]}</h2><p>Please don&apos;t close this window.</p></div>}</>}
function Field({label,value,error,onChange,...rest}:{label:string;value:string;error?:string;onChange:(v:string)=>void;[x:string]:unknown}){return <label className={error?"error":""}><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} {...rest}/><small>{error}</small></label>}
