"use client";
import { useRouter } from "next/navigation";
import { Check, MapPin, Star } from "lucide-react";
import { Back, BookingSummary, Header } from "../../components";
import { boardingPoints, dropPoints, schedules } from "../../data";
import { useBooking } from "../../store";

export default function Trip(){const {booking,update}=useBooking();const router=useRouter();const trip=schedules.find(x=>x.id===booking.scheduleId)||schedules[0];const ready=booking.boarding&&booking.drop;
return <><Header/><main className="page booking-page"><Back href="/search" label="Back to results"/><div className="trip-title"><div><span className="eyebrow">{trip.name}</span><h1>{trip.vehicle}</h1><p><Star fill="currentColor"/> {trip.rating} · {trip.seatsLeft} seats left</p></div><div><b>₹{trip.price.toLocaleString("en-IN")}</b><span>per {trip.mode==="bus"?"seat":"vehicle"}</span></div></div><div className="booking-grid"><div><section className="trip-map"><div className="map-label delhi">New Delhi<i/></div><svg viewBox="0 0 600 280"><path d="M90 55 C190 80 195 160 300 140 S400 200 510 235"/><path className="route-path" d="M90 55 C190 80 195 160 300 140 S400 200 510 235"/></svg><div className="map-label jaipur">Jaipur<i/></div></section><section className="timeline"><div><i/><b>{trip.departure}</b><span>New Delhi</span><small>Kashmiri Gate ISBT</small></div><em>{trip.duration}<br/>281 km</em><div><i/><b>{trip.arrival}</b><span>Jaipur</span><small>Sindhi Camp Bus Stand</small></div></section><section><span className="eyebrow">Included in your ride</span><div className="amenity-grid">{trip.amenities.map(x=><div key={x}><Check/>{x}</div>)}</div></section><PointPicker title="Choose your boarding point" points={boardingPoints} value={booking.boarding} onChange={boarding=>update({boarding})}/><PointPicker title="Choose your drop point" points={dropPoints} value={booking.drop} onChange={drop=>update({drop})}/></div><div><BookingSummary/><button disabled={!ready} className="primary wide" onClick={()=>router.push("/select-seat")}>Continue to seats</button>{!ready&&<small className="hint">Select both points to continue</small>}</div></div></main></>}
function PointPicker({title,points,value,onChange}:{title:string;points:string[];value:string;onChange:(x:string)=>void}){return <section className="point-picker"><span className="eyebrow">{title}</span>{points.map(p=><label className={value===p?"selected":""} key={p}><input type="radio" checked={value===p} onChange={()=>onChange(p)}/><MapPin/><span>{p.split(" · ")[0]}<small>{p.split(" · ")[1]||"Drop point"}</small></span><i/></label>)}</section>}
