"use client";
import { useRouter } from "next/navigation";
import { Armchair, Check } from "lucide-react";
import { Back, BookingSummary, Header, Progress } from "../components";
import { addOns, schedules } from "../data";
import { useBooking } from "../store";

const seats=Array.from({length:24},(_,i)=>`${Math.floor(i/4)+1}${"ABCD"[i%4]}`);const booked=["1B","2C","4A","5D"];
export default function SelectSeat(){const {booking,update}=useBooking();const router=useRouter();const trip=schedules.find(x=>x.id===booking.scheduleId)||schedules[0];const isBus=trip.mode==="bus";const target=booking.search.travellers;
 const toggle=(seat:string)=>{if(booked.includes(seat))return;const on=booking.seats.includes(seat);if(!on&&booking.seats.length>=target)return;update({seats:on?booking.seats.filter(x=>x!==seat):[...booking.seats,seat]})};
 const toggleAddon=(id:string)=>update({addOns:booking.addOns.includes(id)?booking.addOns.filter(x=>x!==id):[...booking.addOns,id]});
 const canContinue=!isBus||booking.seats.length===target;
 return <><Header/><main className="page booking-page"><Back href="/trip/demo" label="Journey details"/><Progress step={1}/><div className="booking-grid"><div><section className="seat-section"><span className="eyebrow">{isBus?"Choose your seats":"Your vehicle"}</span><h1>{isBus?`${target} ${target===1?"seat":"seats"}, together if you like.`:"A private ride, entirely yours."}</h1>{isBus?<><div className="seat-legend"><span><i/>Available</span><span><i className="selected"/>Selected</span><span><i className="booked"/>Booked</span></div><div className="bus"><div className="driver"><span>FRONT</span><Armchair/></div><div className="seat-grid">{seats.map((s,i)=><button key={s} disabled={booked.includes(s)} aria-label={`Seat ${s}${booked.includes(s)?", booked":booking.seats.includes(s)?", selected":""}`} className={`${booking.seats.includes(s)?"selected":""} ${booked.includes(s)?"booked":""} ${(i%4)===2?"aisle":""}`} onClick={()=>toggle(s)}><Armchair/><span>{s}</span></button>)}</div></div></>:<div className="vehicle-selected"><div className="car-silhouette"/><div><span>Selected vehicle</span><h3>{trip.vehicle}</h3><p>Private · 6 seats · 3 bags</p></div><Check/></div>}</section><section className="addons"><span className="eyebrow">Make the journey yours</span><h2>Add a little more ease.</h2>{addOns.map(a=><label className={booking.addOns.includes(a.id)?"selected":""} key={a.id}><input type="checkbox" checked={booking.addOns.includes(a.id)} onChange={()=>toggleAddon(a.id)}/><span><b>{a.name}</b><small>{a.note}</small></span><strong>+ ₹{a.price}</strong><i>{booking.addOns.includes(a.id)&&<Check/>}</i></label>)}</section></div><div><BookingSummary/><button disabled={!canContinue} className="primary wide" onClick={()=>router.push("/checkout")}>Continue to traveller</button>{!canContinue&&<small className="hint">Choose {target-booking.seats.length} more seat{target-booking.seats.length===1?"":"s"}</small>}</div></div></main></>}
